### ISSUE TITLE
Fakturafunktion - addRow

### ISSUE THREAD

**Issue by PtrLarsson** [imagine-it/fakturan.nu-api-v2-client-php#3]
Skapa en funktion för att lägga till en rad på en faktura som tar emot ett produktobjekt, antal och andra eventuella overrides

**Comment by johantell** [comment]
@jontebol Hur sköter ruby-gemet detta? Tänker att det är bra om de gör på samma sätt...

**Comment by jontebol** [comment]
Är inte helt med på vad @PtrLarsson menar med ev. overrides, men om man bara pratar om att skapa en faktura med rader så kan man göra på lite olika sätt:

``` ruby
i = Fakturan::Invoice.new
i.rows.build(product_name: "Sture") # Denna lägger till en rad

i.rows = [Fakturan::Row.new(product_name: "Sven"), Fakturan::Row.new(product_name: "Arne")] # Denna sätter alla rader

i.rows = [{product_name: "Leif"}] # Denna sätter alla rader

# Sen kan man förstås skapa en faktura i ett svep, vilket man ju bör om man har möjlighet (eftersom allt då sparas samtidigt i en transaction):
Fakturan::Invoice.create(date: Date.today, rows: [{product_name: "Birka"}, {product_name: "Borka"}])
```

**Comment by PtrLarsson** [comment]
Det jag menar med eventuella overrides är t.ex. rabatt, moms, fakturadatum, betalningsvilkor och sånt

**Comment by johantell** [comment]
@PtrLarsson Visst är detta gjort? om inte får du öppna igen!

**Comment by jontebol** [comment]
Jag antar att det är @PtrLarsson du frågar?

**Comment by johantell** [comment]
ja... Gjorde jag inte det? :P

**Comment by jontebol** [comment]
U messin with ma mind!

**Comment by PtrLarsson** [comment]
:+1:
